facebook:
  client:
    clientId: 414665505536880
    clientSecret: e85a30ea55b5c775fa8565a76df70987
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: 1ed84cede28feb9d8d2b
    clientSecret: 29a21404982ced497433c2eed92f9d3d249b356a
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

spring:
  application:
    name: SocialMediaWiki
  profiles:
      # The commented value for `active` can be replaced with valid spring profiles to load.
      # Otherwise, it will be filled in by maven when building the WAR file
      # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
      active: prod

  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://sql9.freemysqlhosting.net:3306/sql9164064
      username: sql9164064
      password: 4d2LydmE7k
      continueOnError: true
      initialize: false
      initialSize: 0
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 5000
      minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        event.merge.entity_copy_observer: allow
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: validate
        temp:
          use_jdbc_metadata_defaults: false

#  jpa:
#    database: MYSQL
#
#    properties.hibernate:
#      ddl-auto: create
#      enable_lazy_load_no_trans: true
#
#  datasource:
#    url: jdbc:mysql://sql9.freemysqlhosting.net:3306/sql9164064
#    username: sql9164064
#    password: 4d2LydmE7k
#    driver-class-name: com.mysql.jdbc.Driver

#    http://www.phpmyadmin.co/